TRUNCATE cars, models, brands RESTART IDENTITY CASCADE;

-- Марки
INSERT INTO brands (name) VALUES ('Toyota');
INSERT INTO brands (name) VALUES ('BMW');
INSERT INTO brands (name) VALUES ('Lada');
INSERT INTO brands (name) VALUES ('Mercedes');
INSERT INTO brands (name) VALUES ('Audi');
INSERT INTO brands (name) VALUES ('Kia');
INSERT INTO brands (name) VALUES ('Porsche');

-- Модели
INSERT INTO models (brand_id, name) VALUES ((SELECT id FROM brands WHERE name = 'Porsche'), '911');
INSERT INTO models (brand_id, name) VALUES ((SELECT id FROM brands WHERE name = 'Porsche'), '911 Turbo');
INSERT INTO models (brand_id, name) VALUES ((SELECT id FROM brands WHERE name = 'Porsche'), '911 Turbo S');
INSERT INTO models (brand_id, name) VALUES ((SELECT id FROM brands WHERE name = 'Porsche'), 'Panamera');
INSERT INTO models (brand_id, name) VALUES ((SELECT id FROM brands WHERE name = 'Toyota'), 'Camry');
INSERT INTO models (brand_id, name) VALUES ((SELECT id FROM brands WHERE name = 'Toyota'), 'Corolla');
INSERT INTO models (brand_id, name) VALUES ((SELECT id FROM brands WHERE name = 'Toyota'), 'RAV4');
INSERT INTO models (brand_id, name) VALUES ((SELECT id FROM brands WHERE name = 'Toyota'), 'Land Cruiser');
INSERT INTO models (brand_id, name) VALUES ((SELECT id FROM brands WHERE name = 'BMW'), 'X5');
INSERT INTO models (brand_id, name) VALUES ((SELECT id FROM brands WHERE name = 'BMW'), 'M3');
INSERT INTO models (brand_id, name) VALUES ((SELECT id FROM brands WHERE name = 'BMW'), 'X3');
INSERT INTO models (brand_id, name) VALUES ((SELECT id FROM brands WHERE name = 'BMW'), 'i8');
INSERT INTO models (brand_id, name) VALUES ((SELECT id FROM brands WHERE name = 'Lada'), 'Vesta');
INSERT INTO models (brand_id, name) VALUES ((SELECT id FROM brands WHERE name = 'Lada'), 'Granta');
INSERT INTO models (brand_id, name) VALUES ((SELECT id FROM brands WHERE name = 'Lada'), 'Niva');
INSERT INTO models (brand_id, name) VALUES ((SELECT id FROM brands WHERE name = 'Lada'), 'XRAY');
INSERT INTO models (brand_id, name) VALUES ((SELECT id FROM brands WHERE name = 'Mercedes'), 'E-Class');
INSERT INTO models (brand_id, name) VALUES ((SELECT id FROM brands WHERE name = 'Mercedes'), 'C-Class');
INSERT INTO models (brand_id, name) VALUES ((SELECT id FROM brands WHERE name = 'Mercedes'), 'GLC');
INSERT INTO models (brand_id, name) VALUES ((SELECT id FROM brands WHERE name = 'Mercedes'), 'S-Class');
INSERT INTO models (brand_id, name) VALUES ((SELECT id FROM brands WHERE name = 'Audi'), 'A4');
INSERT INTO models (brand_id, name) VALUES ((SELECT id FROM brands WHERE name = 'Audi'), 'A6');
INSERT INTO models (brand_id, name) VALUES ((SELECT id FROM brands WHERE name = 'Audi'), 'Q5');
INSERT INTO models (brand_id, name) VALUES ((SELECT id FROM brands WHERE name = 'Audi'), 'Q7');
INSERT INTO models (brand_id, name) VALUES ((SELECT id FROM brands WHERE name = 'Kia'), 'Rio');
INSERT INTO models (brand_id, name) VALUES ((SELECT id FROM brands WHERE name = 'Kia'), 'Sportage');
INSERT INTO models (brand_id, name) VALUES ((SELECT id FROM brands WHERE name = 'Kia'), 'Sorento');
INSERT INTO models (brand_id, name) VALUES ((SELECT id FROM brands WHERE name = 'Kia'), 'Ceed');

-- Автомобили
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = '911' AND brand_id = (SELECT id FROM brands WHERE name = 'Porsche')), 2022, 10000);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = '911 Turbo' AND brand_id = (SELECT id FROM brands WHERE name = 'Porsche')), 2023, 15000);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = '911 Turbo S' AND brand_id = (SELECT id FROM brands WHERE name = 'Porsche')), 2023, 18000);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Panamera' AND brand_id = (SELECT id FROM brands WHERE name = 'Porsche')), 2021, 12000);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Camry' AND brand_id = (SELECT id FROM brands WHERE name = 'Toyota')), 2015, 2076);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Camry' AND brand_id = (SELECT id FROM brands WHERE name = 'Toyota')), 2019, 2745);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Camry' AND brand_id = (SELECT id FROM brands WHERE name = 'Toyota')), 2020, 2045);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Camry' AND brand_id = (SELECT id FROM brands WHERE name = 'Toyota')), 2019, 4418);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Corolla' AND brand_id = (SELECT id FROM brands WHERE name = 'Toyota')), 2016, 3981);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Corolla' AND brand_id = (SELECT id FROM brands WHERE name = 'Toyota')), 2020, 2518);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Corolla' AND brand_id = (SELECT id FROM brands WHERE name = 'Toyota')), 2020, 1248);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Corolla' AND brand_id = (SELECT id FROM brands WHERE name = 'Toyota')), 2022, 5107);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Corolla' AND brand_id = (SELECT id FROM brands WHERE name = 'Toyota')), 2016, 1472);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'RAV4' AND brand_id = (SELECT id FROM brands WHERE name = 'Toyota')), 2023, 871);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'RAV4' AND brand_id = (SELECT id FROM brands WHERE name = 'Toyota')), 2016, 3488);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'RAV4' AND brand_id = (SELECT id FROM brands WHERE name = 'Toyota')), 2020, 874);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'RAV4' AND brand_id = (SELECT id FROM brands WHERE name = 'Toyota')), 2022, 4834);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'RAV4' AND brand_id = (SELECT id FROM brands WHERE name = 'Toyota')), 2019, 645);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Land Cruiser' AND brand_id = (SELECT id FROM brands WHERE name = 'Toyota')), 2022, 3355);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Land Cruiser' AND brand_id = (SELECT id FROM brands WHERE name = 'Toyota')), 2020, 4083);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Land Cruiser' AND brand_id = (SELECT id FROM brands WHERE name = 'Toyota')), 2023, 3412);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Land Cruiser' AND brand_id = (SELECT id FROM brands WHERE name = 'Toyota')), 2021, 3164);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'X5' AND brand_id = (SELECT id FROM brands WHERE name = 'BMW')), 2017, 4298);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'X5' AND brand_id = (SELECT id FROM brands WHERE name = 'BMW')), 2018, 5399);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'X5' AND brand_id = (SELECT id FROM brands WHERE name = 'BMW')), 2016, 1682);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'X5' AND brand_id = (SELECT id FROM brands WHERE name = 'BMW')), 2022, 4076);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'M3' AND brand_id = (SELECT id FROM brands WHERE name = 'BMW')), 2021, 2725);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'M3' AND brand_id = (SELECT id FROM brands WHERE name = 'BMW')), 2023, 2815);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'M3' AND brand_id = (SELECT id FROM brands WHERE name = 'BMW')), 2021, 4247);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'M3' AND brand_id = (SELECT id FROM brands WHERE name = 'BMW')), 2022, 5864);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'X3' AND brand_id = (SELECT id FROM brands WHERE name = 'BMW')), 2022, 1833);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'X3' AND brand_id = (SELECT id FROM brands WHERE name = 'BMW')), 2020, 1150);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'X3' AND brand_id = (SELECT id FROM brands WHERE name = 'BMW')), 2023, 3739);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'X3' AND brand_id = (SELECT id FROM brands WHERE name = 'BMW')), 2020, 1837);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'X3' AND brand_id = (SELECT id FROM brands WHERE name = 'BMW')), 2021, 5022);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'i8' AND brand_id = (SELECT id FROM brands WHERE name = 'BMW')), 2018, 5133);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'i8' AND brand_id = (SELECT id FROM brands WHERE name = 'BMW')), 2022, 2099);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'i8' AND brand_id = (SELECT id FROM brands WHERE name = 'BMW')), 2017, 5422);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'i8' AND brand_id = (SELECT id FROM brands WHERE name = 'BMW')), 2015, 1506);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'i8' AND brand_id = (SELECT id FROM brands WHERE name = 'BMW')), 2019, 4648);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Vesta' AND brand_id = (SELECT id FROM brands WHERE name = 'Lada')), 2023, 4174);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Vesta' AND brand_id = (SELECT id FROM brands WHERE name = 'Lada')), 2018, 2852);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Vesta' AND brand_id = (SELECT id FROM brands WHERE name = 'Lada')), 2015, 2284);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Vesta' AND brand_id = (SELECT id FROM brands WHERE name = 'Lada')), 2015, 2777);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Granta' AND brand_id = (SELECT id FROM brands WHERE name = 'Lada')), 2022, 2316);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Granta' AND brand_id = (SELECT id FROM brands WHERE name = 'Lada')), 2018, 994);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Granta' AND brand_id = (SELECT id FROM brands WHERE name = 'Lada')), 2020, 2990);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Niva' AND brand_id = (SELECT id FROM brands WHERE name = 'Lada')), 2022, 4808);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Niva' AND brand_id = (SELECT id FROM brands WHERE name = 'Lada')), 2016, 3131);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Niva' AND brand_id = (SELECT id FROM brands WHERE name = 'Lada')), 2022, 2620);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Niva' AND brand_id = (SELECT id FROM brands WHERE name = 'Lada')), 2022, 2398);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Niva' AND brand_id = (SELECT id FROM brands WHERE name = 'Lada')), 2017, 1020);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'XRAY' AND brand_id = (SELECT id FROM brands WHERE name = 'Lada')), 2023, 1979);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'XRAY' AND brand_id = (SELECT id FROM brands WHERE name = 'Lada')), 2022, 4278);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'XRAY' AND brand_id = (SELECT id FROM brands WHERE name = 'Lada')), 2023, 5663);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'XRAY' AND brand_id = (SELECT id FROM brands WHERE name = 'Lada')), 2018, 4062);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'XRAY' AND brand_id = (SELECT id FROM brands WHERE name = 'Lada')), 2017, 2227);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'E-Class' AND brand_id = (SELECT id FROM brands WHERE name = 'Mercedes')), 2021, 5069);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'E-Class' AND brand_id = (SELECT id FROM brands WHERE name = 'Mercedes')), 2020, 805);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'E-Class' AND brand_id = (SELECT id FROM brands WHERE name = 'Mercedes')), 2021, 1555);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'C-Class' AND brand_id = (SELECT id FROM brands WHERE name = 'Mercedes')), 2016, 1991);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'C-Class' AND brand_id = (SELECT id FROM brands WHERE name = 'Mercedes')), 2018, 2411);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'C-Class' AND brand_id = (SELECT id FROM brands WHERE name = 'Mercedes')), 2017, 2136);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'C-Class' AND brand_id = (SELECT id FROM brands WHERE name = 'Mercedes')), 2023, 3191);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'GLC' AND brand_id = (SELECT id FROM brands WHERE name = 'Mercedes')), 2020, 1375);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'GLC' AND brand_id = (SELECT id FROM brands WHERE name = 'Mercedes')), 2019, 1942);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'GLC' AND brand_id = (SELECT id FROM brands WHERE name = 'Mercedes')), 2018, 2954);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'S-Class' AND brand_id = (SELECT id FROM brands WHERE name = 'Mercedes')), 2018, 4273);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'S-Class' AND brand_id = (SELECT id FROM brands WHERE name = 'Mercedes')), 2022, 3984);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'S-Class' AND brand_id = (SELECT id FROM brands WHERE name = 'Mercedes')), 2020, 982);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'S-Class' AND brand_id = (SELECT id FROM brands WHERE name = 'Mercedes')), 2017, 4964);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'S-Class' AND brand_id = (SELECT id FROM brands WHERE name = 'Mercedes')), 2020, 4695);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'A4' AND brand_id = (SELECT id FROM brands WHERE name = 'Audi')), 2018, 3171);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'A4' AND brand_id = (SELECT id FROM brands WHERE name = 'Audi')), 2021, 2065);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'A4' AND brand_id = (SELECT id FROM brands WHERE name = 'Audi')), 2020, 2363);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'A4' AND brand_id = (SELECT id FROM brands WHERE name = 'Audi')), 2015, 2896);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'A6' AND brand_id = (SELECT id FROM brands WHERE name = 'Audi')), 2019, 5921);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'A6' AND brand_id = (SELECT id FROM brands WHERE name = 'Audi')), 2023, 1874);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'A6' AND brand_id = (SELECT id FROM brands WHERE name = 'Audi')), 2022, 2403);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'A6' AND brand_id = (SELECT id FROM brands WHERE name = 'Audi')), 2015, 1826);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'A6' AND brand_id = (SELECT id FROM brands WHERE name = 'Audi')), 2020, 3955);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Q5' AND brand_id = (SELECT id FROM brands WHERE name = 'Audi')), 2018, 977);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Q5' AND brand_id = (SELECT id FROM brands WHERE name = 'Audi')), 2018, 4502);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Q5' AND brand_id = (SELECT id FROM brands WHERE name = 'Audi')), 2023, 1954);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Q5' AND brand_id = (SELECT id FROM brands WHERE name = 'Audi')), 2018, 2444);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Q7' AND brand_id = (SELECT id FROM brands WHERE name = 'Audi')), 2015, 2679);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Q7' AND brand_id = (SELECT id FROM brands WHERE name = 'Audi')), 2020, 4596);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Q7' AND brand_id = (SELECT id FROM brands WHERE name = 'Audi')), 2018, 2658);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Rio' AND brand_id = (SELECT id FROM brands WHERE name = 'Kia')), 2017, 5947);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Rio' AND brand_id = (SELECT id FROM brands WHERE name = 'Kia')), 2020, 1475);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Rio' AND brand_id = (SELECT id FROM brands WHERE name = 'Kia')), 2021, 4370);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Sportage' AND brand_id = (SELECT id FROM brands WHERE name = 'Kia')), 2021, 848);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Sportage' AND brand_id = (SELECT id FROM brands WHERE name = 'Kia')), 2022, 1045);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Sportage' AND brand_id = (SELECT id FROM brands WHERE name = 'Kia')), 2018, 3085);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Sportage' AND brand_id = (SELECT id FROM brands WHERE name = 'Kia')), 2021, 2155);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Sorento' AND brand_id = (SELECT id FROM brands WHERE name = 'Kia')), 2015, 2990);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Sorento' AND brand_id = (SELECT id FROM brands WHERE name = 'Kia')), 2021, 1207);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Sorento' AND brand_id = (SELECT id FROM brands WHERE name = 'Kia')), 2018, 4807);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Ceed' AND brand_id = (SELECT id FROM brands WHERE name = 'Kia')), 2023, 678);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Ceed' AND brand_id = (SELECT id FROM brands WHERE name = 'Kia')), 2021, 3536);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Ceed' AND brand_id = (SELECT id FROM brands WHERE name = 'Kia')), 2022, 1253);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Ceed' AND brand_id = (SELECT id FROM brands WHERE name = 'Kia')), 2017, 1657);
INSERT INTO cars (model_id, year, price_thousands) VALUES ((SELECT id FROM models WHERE name = 'Ceed' AND brand_id = (SELECT id FROM brands WHERE name = 'Kia')), 2017, 3536);
