services:
  db:
    image: postgres:18-alpine3.22
    container_name: car_showroom_app-db
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/18/docker
    volumes:
      - pgdata:/var/lib/postgresql/18/docker
      - ../migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ../server
      dockerfile: ../deploy/server.Dockerfile
    container_name: car_showroom_app-server
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${APP_PORT}:8080"
    env_file:
      - .env

volumes:
  pgdata:
